src/services/download-service.ts

Remove target attribute to check if it breaks download logic on iOS

[WEB][Download] V7 downloading plug in isnt working on IOS 16.5 version

---

README.md
src/download.tsx

issue:
when plugin added to more plugin the label didnt translated
solution:
add option to translate the label

fix(SUP-38095):add Spanish's translation for downloads plugin

---

src/components/download-overlay/download-overlay.tsx
translations/en.i18n.json

screen reader reads the file name in the download button, 
change it to “Click to download the video”
solves [FEC-13295](https://kaltura.atlassian.net/browse/FEC-13295)
[FEC-13295]: https://kaltura.atlassian.net/browse/FEC-13295?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13295) Download plugin - Accessibility - Need to change the download button lable in the download overlay

---

cypress/e2e/downloads.cy.ts
package.json
src/download.tsx
src/services/download-service.ts
yarn.lock

add support for downloading image.
if the player is image player then the expected behavior is that once clicking on the download, the image file will be directly downloaded and the overlay will not show.

feat: support image download

---

src/download-plugin-manager.tsx
src/services/download-service.ts

in case of an image player, there is a possibility that the HEAD request with `raw` service will fail.
the solution is to add a fallback option by trying to get the image from the image source, that is using the thumbnail service.

feat: add fallback to image download

---

src/services/download-service.ts

**the issue:**
in image entry case, there are no flavors and no captions, but there might be attachments. in case there are no attachments as well, the request to BE to get the downloadUrls is failing; therefore, the download icon is absent.
**solution:**
make the multiRequest to get the download urls, only if at least 1 of the arrays (flavors/captions/attachments) is not empty.
Solves FEC-13452

fix(FEC-13452): download not working for image if no attachments

---

src/components/sources-list/sources-list.tsx
src/download.tsx
src/services/download-service.ts

**the issue:**
when loading a YT entry and clicking the download icon button, there is a source to download (with image icon), although there are no flavors for youtube entries.
**solution:**
render download item for image only if `imageUrl` has a value; render sources (default and flavors) only if array of flavors is not empty - it is possible to have a youtube entry, which has no flavors, but has captions which we would like to allow downloading.
Solves FEC-13455

fix(FEC-13455): download is failing for youtube entries

---

src/download.tsx

Due to the way KMS handles playlists, loadMedia callback is called twice without a reset, which causes the upper bar icon to be added twice
Solution - add a check that upper bar icon was not already added
Resolves FEC-13473

fix(FEC-13473): Player v7 | Playlist | Download button is being duplicated.

---

src/components/download-overlay-button/download-overlay-button.tsx

**issue:**
When embed player in a form element and click on the plugin button, the page refreshes.
**solution:**
add type=button on the plugin button
solves [SUP-39294](https://kaltura.atlassian.net/browse/SUP-39294)
[SUP-39294]: https://kaltura.atlassian.net/browse/SUP-39294?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(SUP-39294): Page refreshes after clicking on player buttons

---

src/download.tsx
src/index.ts

**fix: Wrong and inconsistent order of plugins**
**fix: Plugins buttons sometimes display with the wrong icon**
**solves: [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517) [FEC-13517](https://kaltura.atlassian.net/browse/FEC-13517)**
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[FEC-13517]: https://kaltura.atlassian.net/browse/FEC-13517?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
https://github.com/kaltura/playkit-js-ui-managers/pull/51
https://github.com/kaltura/playkit-js-transcript/pull/175
https://github.com/kaltura/playkit-js-share/pull/38
https://github.com/kaltura/playkit-js-moderation/pull/74 …

fix(FEC-13517): Wrong and inconsistent order of plugins

---

src/components/captions-list/captions-list.tsx
src/providers/get-download-url-loader.ts
src/services/download-service.ts

**Issue:**
When there is one caption on status "processing" the download button is not displayed on the player even if we have additional captions on the entry 
**Root cause:**
There is request for BE to get all the urls for the captions, the request for the caption with status "processing" return kalturaApiException so all the request returns as error as a result the download plugin is not displayed.
**Solution:**
Send "false" in the doRequest as "requestsMustSucceed" so even if one of the caption is not ready the response returns with the other urls.
Since the exception result is removed from the response, the response and the request arrays is not necessarily arranged in the same indexes so set the urls according to the captionAssetId from the url.
part of the fix here - …

fix(SUP-41001): Download button not available

---

src/components/captions-list/captions-list.tsx

**Issue:**
The first captions is being duplicated in the caption list
**Root cause:**
If there is no default caption (on the entry) player set the first captions form the list as the default and displays it on the download dialog, since caption.isDefault returns false we display this captions also in the hide captions so when user click on "More captions" he will see the first caption again.
**Solution:**
Check if caption is not the default by the user **and** it's not the default by the player.
Solves [FEC-13868](https://kaltura.atlassian.net/browse/FEC-13868)
[FEC-13868]: https://kaltura.atlassian.net/browse/FEC-13868?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(FEC-13868): Player v7 | Download | Default language is being duplicated on kms.

---

src/components/download-overlay/download-overlay.tsx
src/download-plugin-manager.tsx
src/download.tsx

**the issue:**
`download_close` event is being reported to analytics too many times.
whenever a media is loaded, we set `showOverlay` to `false`, which sends event to kava as if the overlay was closed by user (which was not).
**solution:**
distinguish between when we set `showOverlay` value for managing its state, and when we set the value because of a user interaction.
Solves FEC-13889

fix(FEC-13889): download_close event being reported too many times

---

src/download.tsx

**the issue:**
`showOverlay` api was removed because it was not clear who is using it, which caused a regression in audio player when clicking on download button.
**solution:**
bring back the api.
Solves FEC-13728

fix(FEC-13728): bring back showOverlay api

---

src/components/download-overlay/download-overlay.scss
src/download-plugin-manager.tsx

While overlay is active, remove blur from interactive area, and change z index of the overlay so that toasts will appear on top of it
Resolves FEC-14086

fix(FEC-14086): Player v7 | Download plugin overlay doesnt match figma.

---

src/components/sources-list/sources-list.tsx

Filter out flavors which have an empty downloadUrl

fix: filter out flavors with no downloadUrl

---

src/components/sources-list/sources-list.tsx

Filter out flavors with height 0 to not show captions as sources

fix: filter out flavors with height 0

---

src/components/attachments-list/attachments-list.tsx
src/components/captions-list/captions-list.tsx
src/components/download-item/download-item.tsx
src/components/download-overlay/download-overlay.tsx
src/components/sources-list/sources-list.tsx

**Issue:** 
When open the download plugin with tab key, focus move to the first element in the modal only if the displayFlavors config is enabled. in case of display only captions or attachment, focus move to the body and not not specific element.
**Fix:**
Add functionality to check if captions/attachment or flavors will be displayed first in the modal, then move the focus according to that and not only according isDefault value (that relevant only to diaplyFlavors and not the rest of the configuration)
Solves [ADA-1514](https://kaltura.atlassian.net/browse/ADA-1514)
[ADA-1514]: https://kaltura.atlassian.net/browse/ADA-1514?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1514): Incorrect focus order is observed when Related Files button is activated.

---

src/components/download-overlay/download-overlay.tsx

Change download div element to h2 element (accessibility requirement) 
solves [ADA-1747](https://kaltura.atlassian.net/browse/ADA-1747)
[ADA-1747]: https://kaltura.atlassian.net/browse/ADA-1747?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(ADA-1747): [BofA] Marketting - Avoid the use of implicit headings

---

src/components/download-overlay-button/download-overlay-button.tsx

This solves https://kaltura.atlassian.net/browse/ADA-1736. 
It sets the Tooltip position to always be bottom-left.
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

fix(ADA-1736) - Tooltip strict position

---

demo/index.html
src/components/download-overlay/download-overlay.tsx
translations/en.i18n.json

This solves https://kaltura.atlassian.net/browse/ADA-1745
It is related to  https://github.com/kaltura/playkit-js-ui/pull/984 and https://github.com/kaltura/playkit-js-info/pull/112
Please add a detailed description of the change, weather it's an enhancement or a bugfix.
If the PR is related to an open issue please link to it.

fix(ADA-1745) - Include modal title into close button aria-label 
